### ISSUE TITLE
Syntax error when running script.

### ISSUE THREAD

**Issue by axlot** [digitalocean/debian-sys-maint-roll-passwd#10]
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'USER 'debian-sys-maint'@'localhost' IDENTIFIED BY 'XXXX' at line 1
fix.sh: line 114: /bin/systemctl: No such file or directory

Done. This system is no longer affected.

NOTE: I changed XXXX where the actual password was printed.

mysql  Ver 14.14 Distrib 5.5.47, for debian-linux-gnu (i686) using readline 6.2

**Comment by rastacalavera** [comment]
Can you elaborate a bit more on how you fixed this? I had a similar error and am running mysql Ver 10.0.31-MariaDB-0ubuntu0.16.04.2 Ubuntu 16.04 and am not sure what exactly you changed in the fix.sh file to point it to the correct location.

**Comment by darkmuggle** [comment]
`fix.sh: line 114: /bin/systemctl: No such file or directory` that syntax error indicates that you are runnning this on an unsupported system -- either a non-Debian/Ubuntu system or one that is out of support.

**Comment by rastacalavera** [comment]
@utlemming my error is different from @axlot and is in line 1 not 114. I've pasted the exact thing below except replaced that huge string with Xs

Logging to /root/mysql-fix-1505774647.log
Updating root with new password
ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'USER 'root'@'localhost' IDENTIFIED BY 'XXXX'at line 1

Can you provide some guidance on addressing this?
Thanks!
