### ISSUE TITLE
Your password does not satisfy the current policy requirements

### ISSUE THREAD

**Issue by fsalomon** [digitalocean/debian-sys-maint-roll-passwd#5]
On some instances I'm getting this error:

`ERROR 1819 (HY000) at line 1: Your password does not satisfy the current policy requirements`

I changed the password manually for those instances, but I thought you might want to generate a more complex password that's likely to satisfy any reasonable password policy.

**Comment by utlemming** [comment]
Fixed.

**Comment by utlemming** [comment]
This is now addressed to meet complexity requirements. Unfortunately, the distro-created user never meets the password complexity requirements set to medium or higher. The new version should meet strict as well.
