### ISSUE TITLE
Hit enter required after running wget command.

### ISSUE THREAD

**Issue by robdeadtech** [digitalocean/debian-sys-maint-roll-passwd#6]
I almost just closed the window after copy pasting the script.
It would be a good idea to say something similar to. 
"You will see the command `$ bash fix.sh` at your terminal prompt. Hit the return key to run the script. If you see the message 'Done. This system is no longer affected.' You are patched."

**Comment by bbashy** [comment]
It's best to get some general Linux knowledge before running scripts as root :|

**Comment by robdeadtech** [comment]
Agreed. I just think it currently looks like one step, when there's two. The wget, then running the script. A person buying a one-click install might need a bit of handholding here.

**Comment by bbashy** [comment]
It could be better. Maybe add a quick PR to make it two code blocks.

**Comment by robdeadtech** [comment]
done!

**Comment by darkmuggle** [comment]
Accepted the PR, so I'll go ahead and close this out. Thank you kindly for your contribution.
