### ISSUE TITLE
mysql: command not found

### ISSUE THREAD

**Issue by posidonius** [digitalocean/debian-sys-maint-roll-passwd#9]
fix.sh: line 95: mysql: command not found

How to debug this problem?

**Comment by utlemming** [comment]
If mysql command is not found, then you likely do not have MySQL installed and are not affected _or_  the path is wrong. After complete removal of MySQ, `/etc/mysql/debian` remains.  Please file a ticket with DigitalOcean support and reference this.

**Comment by posidonius** [comment]
Mysql is installed. Command "which mysql" returns a path. Not sure what to do.
